### ISSUE TITLE
Policy as Code need new templates ones for azure-nextgen

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/templates-policy#21]
We need a azure-nextgen policy pack template for azure-nextgen resources

We need a template for:
pulumi policy pack new azure-typescript
pulumi policy pack new azure-py
pulumi policy pack new azure-javascript
pulumi policy pack new azure-cs

**Comment by aureq** [comment]
@tusharshahrs I believe we should be able to close this issue, right?

**Comment by tusharshahrs** [comment]
New Premium Policy as Code resolves this.
